// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNgKGirzlkAO6-oap5cE-n129q-OY4Bs',
    appId: '1:939391174644:web:e8a21c00dd8db76dd99ba1',
    messagingSenderId: '939391174644',
    projectId: 'lapse-program-takip',
    authDomain: 'lapse-program-takip.firebaseapp.com',
    storageBucket: 'lapse-program-takip.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1awsR5XhZ-aTIyKLdXreAf9GCFNBQAI',
    appId: '1:939391174644:android:7274d61221640609d99ba1',
    messagingSenderId: '939391174644',
    projectId: 'lapse-program-takip',
    storageBucket: 'lapse-program-takip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYCxh8Ar400XHyS0ksKMB7gv1_Pf8-o8',
    appId: '1:939391174644:ios:562a796242b837afd99ba1',
    messagingSenderId: '939391174644',
    projectId: 'lapse-program-takip',
    storageBucket: 'lapse-program-takip.firebasestorage.app',
    iosBundleId: 'com.emircandan.lapse',
  );

}